version: 2.1

jobs:
  build-geth:
    docker:
      - image: cimg/go:1.18
    resource_class: medium
    steps:
      - checkout
      - run:
          command: go run build/ci.go install
  unit-test:
    resource_class: medium
    docker:
      - image: cimg/go:1.18
    steps:
      - checkout
      - run:
          command: go run build/ci.go test
  lint-geth:
    resource_class: medium
    docker:
      - image: cimg/go:1.18
    steps:
      - checkout
      - run:
          command: go run build/ci.go lint

  build-dockerfile:
    docker:
      - image: cimg/base:2022.04
    parameters:
      image-name:
        description: Image name
        type: string
      image-tag:
        description: Image tag
        type: string
      target:
        description: Dockerfile target
        type: string
        default: ""
      dockerfile:
        description: Dockerfile to use
        type: string
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.12
      - run:
          name: Build
          command: |
            echo "$DOCKER_PASS" | docker login -u "$DOCKER_USERNAME" --password-stdin
            docker build -t "ethereumoptimism/<<parameters.image-name>>:<<parameters.image-tag>>" -f <<parameters.dockerfile>> <<#parameters.target>>--target <<parameters.target>><</parameters.target>> .
            docker push "ethereumoptimism/<<parameters.image-name>>:<<parameters.image-tag>>"

workflows:
  main:
    jobs:
      - build-geth:
          name: Build geth
      - unit-test:
          name: Run unit tests for geth
      - lint-geth:
          name: Run linter over geth
      - build-dockerfile:
          context:
            - optimism
          filters:
            branches:
              only:
                - optimism
          image-name: reference-optimistic-geth
          image-tag: latest
          dockerfile: Dockerfile
          name: Build reference-optimistic-geth develop
      - build-dockerfile:
          context:
            - optimism
          image-name: reference-optimistic-geth
          image-tag: $CIRCLE_SHA1
          dockerfile: Dockerfile
          name: Build reference-optimistic-geth per-commit
